/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProvidersRouteImport } from './routes/_app.providers'
import { Route as AppModelsRouteImport } from './routes/_app.models'
import { Route as AppLogsRouteImport } from './routes/_app.logs'
import { Route as AppKeysRouteImport } from './routes/_app.keys'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppDocsRouteImport } from './routes/_app.docs'
import { Route as AppCheckerRouteImport } from './routes/_app.checker'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersRoute = AppProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppRoute,
} as any)
const AppModelsRoute = AppModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppKeysRoute = AppKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckerRoute = AppCheckerRouteImport.update({
  id: '/checker',
  path: '/checker',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/checker': typeof AppCheckerRoute
  '/docs': typeof AppDocsRoute
  '/history': typeof AppHistoryRoute
  '/keys': typeof AppKeysRoute
  '/logs': typeof AppLogsRoute
  '/models': typeof AppModelsRoute
  '/providers': typeof AppProvidersRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof AppAnalyticsRoute
  '/checker': typeof AppCheckerRoute
  '/docs': typeof AppDocsRoute
  '/history': typeof AppHistoryRoute
  '/keys': typeof AppKeysRoute
  '/logs': typeof AppLogsRoute
  '/models': typeof AppModelsRoute
  '/providers': typeof AppProvidersRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/checker': typeof AppCheckerRoute
  '/_app/docs': typeof AppDocsRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/keys': typeof AppKeysRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/models': typeof AppModelsRoute
  '/_app/providers': typeof AppProvidersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/checker'
    | '/docs'
    | '/history'
    | '/keys'
    | '/logs'
    | '/models'
    | '/providers'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/checker'
    | '/docs'
    | '/history'
    | '/keys'
    | '/logs'
    | '/models'
    | '/providers'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/analytics'
    | '/_app/checker'
    | '/_app/docs'
    | '/_app/history'
    | '/_app/keys'
    | '/_app/logs'
    | '/_app/models'
    | '/_app/providers'
    | '/_app/settings'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/providers': {
      id: '/_app/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AppProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/models': {
      id: '/_app/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AppModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keys': {
      id: '/_app/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AppKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/docs': {
      id: '/_app/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checker': {
      id: '/_app/checker'
      path: '/checker'
      fullPath: '/checker'
      preLoaderRoute: typeof AppCheckerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCheckerRoute: typeof AppCheckerRoute
  AppDocsRoute: typeof AppDocsRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppKeysRoute: typeof AppKeysRoute
  AppLogsRoute: typeof AppLogsRoute
  AppModelsRoute: typeof AppModelsRoute
  AppProvidersRoute: typeof AppProvidersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCheckerRoute: AppCheckerRoute,
  AppDocsRoute: AppDocsRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppKeysRoute: AppKeysRoute,
  AppLogsRoute: AppLogsRoute,
  AppModelsRoute: AppModelsRoute,
  AppProvidersRoute: AppProvidersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
